#define BTN2_PID  PID_RPM
#define BTN3_PID  PID_SPEED
#define BTN4_PID  PID_ENGINE_LOAD
#define BTN5_PID  PID_THROTTLE
#define BTN6_PID  PID_ENGINE_OIL_TEMP
#define BTN7_PID  PID_INTAKE_TEMP
#define BTN8_PID  PID_BAROMETRIC
